name: Infra - Terraform

on:
  push:
    branches:
      - DEV
      - main
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/infra.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/infra.yml'

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-infra
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v5

      - name: Authentification GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.ref == 'refs/heads/DEV' || github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
